// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearHistory():Promise<main.GuardianStatus>;

export function ExitApplication():Promise<void>;

export function GetStatus():Promise<main.GuardianStatus>;

export function HideToTray():Promise<void>;

export function SetGuardianEnabled(arg1:boolean):Promise<main.GuardianStatus>;

export function ShowWindow():Promise<void>;
