// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function ExitApplication() {
  return window['go']['main']['App']['ExitApplication']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function HideToTray() {
  return window['go']['main']['App']['HideToTray']();
}

export function SetGuardianEnabled(arg1) {
  return window['go']['main']['App']['SetGuardianEnabled'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}
